plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/dingcaozhi/.openclaw/workspace/mwc2026-agent-news"
publishOrigin = "default"
base = "/Users/dingcaozhi/.openclaw/workspace/mwc2026-agent-news"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/rss.xml"
to = "/rss.xml"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]